baseURL = "https://srldf.org/"
languageCode = "en-us"
title = "Security Research Legal Defense Fund"

[params]
  description = "The Security Research Legal Defense Fund provides legal support and resources for security researchers facing legal threats for good-faith vulnerability disclosure."
  donateEmail = "donate@srldf.org"
  contactEmail = "info@srldf.org"
  securityEmail = "security@srldf.org"
  googleTagManagerID = "GTM-N62F2L2"
  googleAnalyticsID = "G-RTTFRMLYPH"
  ogImage = "images/srldf-org.png"
  blueskyURL = "https://bsky.app/profile/srldf.bsky.social"
  linkedinURL = "https://www.linkedin.com/company/security-research-legal-defense-fund"
  twitterURL = "https://x.com/securityldf"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML"]
